services:
  db:
    image: postgres:15-alpine
    container_name: notes_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER = postgres
      POSTGRES_PASSWORD = 1618
      POSTGRES_DB = notesdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
    db_data: 
